version: '3'
services:
  db:
    container_name: banco
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: projeto-final
    ports: 
      - 3306:3306
    volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    
